### ISSUE TITLE
:v

### ISSUE THREAD

**Issue by Dang-pig** [brainstormerjr/HelloWorldOS#2]
But how to run this os?

**Comment by MrDev139** [comment]
I think there's an iso that you can download and just write it on a usb (mbr legacy bios)

**Comment by Dang-pig** [comment]
But this OS's engineers are learning to build ISO file, so I guess we have to wait

**Comment by MrMan314** [comment]
See: #11
(the isos are located in the downloads/ and src/ folders)

**Comment by brainstormerjr** [comment]
Yup thanks to MrMan314 we have downloadable iso files from the site :D
