### ISSUE TITLE
My dad is on the floor

### ISSUE THREAD

**Issue by pgbito** [brainstormerjr/HelloWorldOS#3]
I installed the os, then my pc flew thru the window, and it crashed into my dad's face while he was cutting grass in the Backyard 
this os is so dangerous!

**Comment by brainstormerjr** [comment]
We sorry for any human damage caused by our lightweight and groundbreaking operating system, and we offer our deepest apologies to your father. However, Hello World Inc. is not fiscally responsible for any health-related issues caused by Hello World OS.
