### ISSUE TITLE
Why can't I install fortnite on it i need my wenegade waidoh

### ISSUE THREAD

**Issue by Fant0mic** [brainstormerjr/HelloWorldOS#4]
No ,seriously

**Comment by rubencosta13** [comment]
I think that Fortnite is not really good otherwise Hello World OS would have supported it in the first place. I'd suggest you to download Tetris instead of Fortnite

Good Luck

**Comment by ABadNameSniper** [comment]
> I think that Fortnite is not really good otherwise Hello World OS would have supported it in the first place. I'd suggest you to download Tetris instead of Fortnite
> 
> Good Luck

I think this implication means that Tetris is supported on Hello World OS. Excellent.

**Comment by brainstormerjr** [comment]
The entire point of Hello World OS is to provide a more minimalistic experience, so Fortnite is not and will never be supported on this operating system.

As for playing Tetris, although that this game is more minimalistic and aligns slightly more with our vision, the support for Tetris will significantly slow down our operating system and will increase the size of our operating system by orders of magnitude.

If you wish to play Tetris on a minimal operating system, Tetris OS developed by jdh may have what you need: https://www.youtube.com/watch?v=FaILnmUYS_U
