### ISSUE TITLE
Output???

### ISSUE THREAD

**Issue by PiterDev** [brainstormerjr/HelloWorldOS#5]
When I run the system I see output! This is incredibly infuriating as I hate when my operating systems do something. I was promised a lightweight system and I see text??? This is incredibly displeasing for me and I think I'll go back to unplugging my monitor from my PC. Pls fix

**Comment by maciejoliwa** [comment]
I added a pull request fixing this issue, we'll if they'll merge it into HelloWorldOS, or if they make another version without text.

**Comment by brainstormerjr** [comment]
A branch has been made for a lite version of the operating system due to high demand.
