### ISSUE TITLE
Attempting to boot pro.elf on 1mb RAM in qemu fails to load, requiring 2mb, which is excessive

### ISSUE THREAD

**Issue by jclocks** [brainstormerjr/HelloWorldOS#8]
I don't understand how the professional development teams behind this "world class product" expect this operating system to catch on when it requires 2 MB RAM to boot. In times like these where we are undergoing a chip shortage, RAM conversation is critical, and I find the use of two whole megabytes to be wholly unacceptable.

I would like my money back and an apology

**Comment by MrMan314** [comment]
QEMU won't initialize the display if the memory is less than 1032193 bytes.  Memory is counted in MiB, meaning that it is 0.98437595367 MiB, or 1008.000977 KiB.  
The OS currently runs on a minimum of 1064961 bytes, or 1.015625954 MiB, or 1040.000977 KiB.

**Comment by jclocks** [comment]
Fair enough. Misunderstanding answered, apology unneeded. You can keep your money... e_e

(Jokes aside, it's amazing how tiny you can make a bootable OS, even if one that solely displays text for a meme. Good stuff.)
